import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { requireOrganizationContext } from "@/lib/auth/server";
export const dynamic = "force-dynamic";
type CompanyRow = { id: string; name: string; industry: string | null; website_url: string | null; description: string | null; sales_recommendations: { recommended_on: string; reason: string; status: string }[] };
export default async function CompaniesPage({ searchParams }: { searchParams: Promise<{ organizationId?: string; q?: string; industry?: string; sort?: string }> }) {
  const query = await searchParams; if (!query.organizationId) return <main className="p-8">組織を選択してください。</main>; const { supabase, organization } = await requireOrganizationContext(query.organizationId);
  const { data, error } = await supabase.from("companies").select("id,name,industry,website_url,description,sales_recommendations(recommended_on,reason,status)").eq("organization_id", query.organizationId); if (error) throw error;
  const q = (query.q ?? "").trim().toLocaleLowerCase("ja"); const industry = query.industry ?? ""; let rows = ((data ?? []) as CompanyRow[]).filter((company) => (!q || `${company.name} ${company.industry ?? ""} ${company.description ?? ""}`.toLocaleLowerCase("ja").includes(q)) && (!industry || company.industry === industry)).map((company) => ({ ...company, next: company.sales_recommendations.filter((item) => item.status === "pending").sort((a, b) => a.recommended_on.localeCompare(b.recommended_on))[0] }));
  rows = rows.sort(query.sort === "recommended" ? (a, b) => (a.next?.recommended_on ?? "9999").localeCompare(b.next?.recommended_on ?? "9999") : query.sort === "industry" ? (a, b) => (a.industry ?? "").localeCompare(b.industry ?? "", "ja") : (a, b) => a.name.localeCompare(b.name, "ja")); const industries = [...new Set(((data ?? []) as CompanyRow[]).map((item) => item.industry).filter(Boolean))] as string[];
  return <AppShell organizationId={query.organizationId} organizationName={organization.name}><main className="page-container"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">営業リスト</p><h1 className="mt-2 text-3xl font-bold">企業一覧</h1></div><Link className="primary-button text-center" href={`/companies/new?organizationId=${query.organizationId}`}>企業を追加</Link></header><form className="card mt-6 grid gap-3 p-4 sm:grid-cols-[1fr_180px_180px_auto]" method="get"><input type="hidden" name="organizationId" value={query.organizationId} /><label className="field-label">検索<input className="field" name="q" defaultValue={query.q} placeholder="会社名・業種・備考" /></label><label className="field-label">業種<select className="field" name="industry" defaultValue={industry}><option value="">すべて</option>{industries.map((value) => <option key={value}>{value}</option>)}</select></label><label className="field-label">並び替え<select className="field" name="sort" defaultValue={query.sort ?? "name"}><option value="name">会社名</option><option value="recommended">推奨日</option><option value="industry">業種</option></select></label><button className="secondary-button self-end">表示</button></form><p className="mt-5 text-sm text-stone-500">{rows.length}社</p>{rows.length ? <div className="mt-3 overflow-hidden rounded-2xl border bg-white"><div className="hidden grid-cols-[1.4fr_1fr_1fr_1.2fr] gap-4 border-b bg-stone-50 px-5 py-3 text-xs font-semibold text-stone-500 md:grid"><span>会社名</span><span>業種</span><span>次回推奨日</span><span>理由</span></div>{rows.map((company) => <Link className="grid gap-2 border-b px-5 py-4 last:border-0 hover:bg-teal-50/50 md:grid-cols-[1.4fr_1fr_1fr_1.2fr] md:gap-4" href={`/companies/${company.id}?organizationId=${query.organizationId}`} key={company.id}><strong>{company.name}</strong><span className="text-sm text-stone-600">{company.industry ?? "未設定"}</span><span className="text-sm font-semibold text-teal-800">{company.next?.recommended_on ?? "推奨なし"}</span><span className="line-clamp-2 text-sm text-stone-600">{company.next?.reason ?? "イベントとルールを登録してください"}</span></Link>)}</div> : <div className="empty-state mt-4"><h2>該当する企業がありません</h2><p>検索条件を変えるか、最初の企業を追加してください。</p></div>}</main></AppShell>;
}
