import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { requireOrganizationContext } from "@/lib/auth/server";
import { scheduleRanges, todayInTokyo } from "@/lib/dates";
export const dynamic = "force-dynamic";
type Item = { id: string; recommended_on: string; reason: string; company_id: string; companies: { id: string; name: string } | { id: string; name: string }[] | null };
function TargetList({ title, items, organizationId, accent = false }: { title: string; items: Item[]; organizationId: string; accent?: boolean }) { return <section className={accent ? "card border-teal-200 bg-teal-950 p-5 text-white" : "card p-5"}><div className="mb-4 flex items-end justify-between"><h2 className="text-xl font-bold">{title}</h2><span className={accent ? "text-sm text-teal-200" : "text-sm text-stone-500"}>{items.length}社</span></div>{items.length ? <ul className="space-y-3">{items.map((item) => { const company = Array.isArray(item.companies) ? item.companies[0] : item.companies; return <li key={item.id}><Link className={accent ? "block rounded-xl bg-white/10 p-4 hover:bg-white/15" : "block rounded-xl bg-stone-50 p-4 hover:bg-stone-100"} href={`/companies/${item.company_id}?organizationId=${organizationId}`}><div className="flex justify-between gap-3"><strong>{company?.name ?? "企業"}</strong><time className="text-sm">{item.recommended_on}</time></div><p className={accent ? "mt-1 text-sm text-teal-100" : "mt-1 text-sm text-stone-600"}>{item.reason}</p></Link></li>; })}</ul> : <div className={accent ? "rounded-xl bg-white/10 p-4 text-teal-100" : "empty-state"}>対象はありません。</div>}</section>; }
export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ organizationId?: string }> }) {
  const { organizationId } = await searchParams; if (!organizationId) return <main className="p-8">組織を選択してください。</main>; const { supabase, organization } = await requireOrganizationContext(organizationId); const range = scheduleRanges(todayInTokyo());
  const [recommendations, companyCount] = await Promise.all([supabase.from("sales_recommendations").select("id,company_id,recommended_on,reason,companies(id,name)").eq("organization_id", organizationId).eq("status", "pending").lte("recommended_on", range.monthEnd).order("recommended_on"), supabase.from("companies").select("id", { count: "exact", head: true }).eq("organization_id", organizationId)]); if (recommendations.error || companyCount.error) throw recommendations.error ?? companyCount.error; const items = (recommendations.data ?? []) as Item[]; const today = items.filter((item) => item.recommended_on <= range.today); const week = items.filter((item) => item.recommended_on > range.today && item.recommended_on <= range.weekEnd); const month = items.filter((item) => item.recommended_on > range.weekEnd);
  return <AppShell organizationId={organizationId} organizationName={organization.name}><main className="page-container"><header className="mb-7"><p className="eyebrow">{organization.name}</p><h1 className="mt-2 text-3xl font-bold">今日の営業対象</h1><p className="mt-2 text-stone-600">期限を迎えた企業を最優先で表示しています。</p></header>{companyCount.count === 0 ? <section className="card mb-7 border-amber-200 bg-amber-50 p-5"><p className="text-xs font-bold text-amber-800">はじめての方へ</p><h2 className="mt-1 text-xl font-bold">4ステップで営業予定を作成</h2><ol className="mt-4 grid gap-3 text-sm sm:grid-cols-4"><li><strong>1. 企業登録</strong><br />会社情報を追加</li><li><strong>2. 営業履歴</strong><br />過去の活動を記録</li><li><strong>3. イベント</strong><br />展示会などを登録</li><li><strong>4. 推奨日確認</strong><br />今日・カレンダーで確認</li></ol><Link className="primary-button mt-5" href={`/companies/new?organizationId=${organizationId}`}>最初の企業を登録</Link></section> : null}<div className="grid gap-5 lg:grid-cols-3"><TargetList title="今日・期限超過" items={today} organizationId={organizationId} accent /><TargetList title="今週" items={week} organizationId={organizationId} /><TargetList title="今月" items={month} organizationId={organizationId} /></div><section className="mt-7 grid gap-4 sm:grid-cols-2"><Link className="card p-5 hover:border-teal-600" href={`/companies/new?organizationId=${organizationId}`}><strong>企業を追加</strong><p className="mt-1 text-sm text-stone-600">新しい営業先を登録します</p></Link><Link className="card p-5 hover:border-teal-600" href={`/companies?organizationId=${organizationId}`}><strong>企業を検索</strong><p className="mt-1 text-sm text-stone-600">外出先でも会社名からすぐ検索</p></Link></section></main></AppShell>;
}
